Telegram:
  BotToken: BOT TOKEN HERE
  Channels:
    CHANNELHERE

Selenium:
  Host: http://localhost:4444/wd/hub
  BrowserDriver: firefox
People:
  - Name: "Matthew Baggett"
    Accounts:
      Business Account:
        connector: CashPlusBankAccount
        auth:
          username: 'username'
          password: 'password'
      Account Name Here:
        connector: CooperativeBankAccount
          auth:
            sort: '012345'
            acct: '98765432'
            security: '0000'
            memorable_date: '2015-01-01'
            first_school: 'first school'
            last_school: 'last school'
            birth_place: berlin
            memorable_name: boris
